language: c

cache:
  directories:
  - $HOME/gnatsd
  - $HOME/nats-streaming-server

sudo: false

compiler: 
  - gcc
  - clang

addons:
  apt:
    packages:
    - valgrind
    - libssl-dev
    - unzip

before_install:
  - bash install_servers.sh

before_script:
  - export PATH=$HOME/gnatsd:$HOME/nats-streaming-server:$PATH
  - mkdir build && cd build

env:
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release" DO_COVERAGE="no"
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release -DNATS_BUILD_WITH_TLS=OFF" DO_COVERAGE="no"
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release -DNATS_MEMCHECK_CMD=`which valgrind`" NATS_TEST_VALGRIND=yes CTEST_OPT="-T memcheck" DO_COVERAGE="no"
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release -DNATS_MEMCHECK_CMD=`which valgrind`" NATS_DEFAULT_TO_LIB_MSG_DELIVERY=yes NATS_TEST_VALGRIND=yes CTEST_OPT="-T memcheck" DO_COVERAGE="no"
  - BUILD_OPT="-DNATS_BUILD_ARCH=64 -DNATS_BUILD_TYPE=Release -DNATS_COVERAGE=ON" DO_COVERAGE="coverage"

script:
  - $TRAVIS_BUILD_DIR/buildOnTravis.sh "$CC" "$DO_COVERAGE" "$BUILD_OPT" "$CTEST_OPT"

notifications:
  email: false

